In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_iris(return_X_y=True)

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state=42)

In [7]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()

In [8]:
gb.fit(X_train,y_train)

GaussianNB()

In [9]:
y_pred = gb.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [11]:
    
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

print(accuracy_score(y_test, y_pred))

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

0.9777777777777777


In [12]:
## assignment - load sns tips dataset and apply naive bayes to predict - day from dataset

In [13]:
tips = sns.load_dataset('tips')

In [14]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [17]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [19]:
tips['day'].value_counts()

,count
day,
Sat,87
Sun,76
Thur,62
Fri,19


In [20]:
X = tips[['total_bill', 'tip', 'sex', 'smoker', 'time', 'size']]
y = tips['day']

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)

In [35]:
X_train.head()

,total_bill,tip,sex,smoker,time,size
0,15.53,3.00,Male,Yes,Dinner,2
1,20.45,3.00,Male,No,Dinner,4
2,34.65,3.68,Male,Yes,Dinner,4
3,25.29,4.71,Male,No,Dinner,4
4,38.01,3.00,Male,Yes,Dinner,4


In [36]:
y_train.head()

,day
234,Sat
227,Sat
180,Sun
5,Sun
56,Sat


In [37]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [38]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [39]:
X_train.head()

,total_bill,tip,sex,smoker,time,size
0,15.53,3.00,1,1,0,2
1,20.45,3.00,1,0,0,4
2,34.65,3.68,1,1,0,4
3,25.29,4.71,1,0,0,4
4,38.01,3.00,1,1,0,4


In [40]:
X_test.head()

,total_bill,tip,sex,smoker,time,size
0,19.82,3.18,Male,No,Dinner,2
1,8.77,2.00,Male,No,Dinner,2
2,24.55,2.00,Male,No,Dinner,4
3,25.89,5.16,Male,Yes,Dinner,4
4,13.00,2.00,Female,Yes,Lunch,2


In [41]:
X_test['sex'] = le1.transform(X_test['sex'].values)
X_test['smoker'] = le2.transform(X_test['smoker'].values)
X_test['time'] = le3.transform(X_test['time'].values)

In [42]:
X_test.head()

,total_bill,tip,sex,smoker,time,size
0,19.82,3.18,1,0,0,2
1,8.77,2.00,1,0,0,2
2,24.55,2.00,1,0,0,4
3,25.89,5.16,1,1,0,4
4,13.00,2.00,0,1,1,2


In [43]:
le_target = LabelEncoder()
y_train = le_target.fit_transform(y_train)
y_test = le_target.transform(y_test)

In [44]:
gb.fit(X_train,y_train)

GaussianNB()

In [45]:
y_pred_tips = gb.predict(X_test)

In [46]:
print(confusion_matrix(y_test, y_pred_tips))
print(classification_report(y_test, y_pred_tips))
print(accuracy_score(y_test, y_pred_tips))

[[ 0  3  0  1]
 [ 0 17 11  0]
 [ 0  7 17  0]
 [ 0  0  0 18]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.63      0.61      0.62        28
           2       0.61      0.71      0.65        24
           3       0.95      1.00      0.97        18

    accuracy                           0.70        74
   macro avg       0.55      0.58      0.56        74
weighted avg       0.67      0.70      0.68        74

0.7027027027027027


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [47]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [48]:
mnb.fit(X_train,y_train)

MultinomialNB()

In [49]:
y_pred = mnb.predict(X_test)

In [50]:
print(confusion_matrix(y_test, y_pred_tips))
print(classification_report(y_test, y_pred_tips))
print(accuracy_score(y_test, y_pred_tips))

[[ 0  3  0  1]
 [ 0 17 11  0]
 [ 0  7 17  0]
 [ 0  0  0 18]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.63      0.61      0.62        28
           2       0.61      0.71      0.65        24
           3       0.95      1.00      0.97        18

    accuracy                           0.70        74
   macro avg       0.55      0.58      0.56        74
weighted avg       0.67      0.70      0.68        74

0.7027027027027027


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
